Repository webcomics/dosage, pull requests merged in 2023-06, with the labels that each got.

#267 Add AwkwardZombie
  dosagelib/plugins/a.py
Labels: enhancement

#248 Test with Python 3.11
  .github/workflows/test.yml
  Jenkinsfile
  pyproject.toml
  tox.ini
Labels: dependencies

#270 Modernize importlib.resources usage
  dosagelib/plugins/comicskingdom.py
  pyproject.toml
Labels: chore

#269 Add Comics
  dosagelib/plugins/a.py
  dosagelib/plugins/c.py
  dosagelib/plugins/d.py
  dosagelib/plugins/s.py
  dosagelib/plugins/v.py
Labels: enhancement
