Repository webcomics/dosage, pull requests merged in 2025-05, with the labels that each got.

#340 Introduce pre-commit and move flake8 there
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  Jenkinsfile
  README.md
  doc/.theme/dir.html
  doc/.theme/static/css/pygments.css
  dosagelib/__init__.py
  dosagelib/__pyinstaller/hook-dosagelib.py
  pyproject.toml
  scripts/tapas.py
  tests/modules/testall.sh
  tox.ini
Labels: chore

#329 PoorlyDrawnLines: Fix after site redesign
  dosagelib/plugins/p.py
Labels: bug

#342 Migrate home-grown logging to stdlib logging (fixes #309)
  dosagelib/__init__.py
  dosagelib/cmd.py
  dosagelib/comic.py
  dosagelib/director.py
  dosagelib/events.py
  dosagelib/loader.py
  dosagelib/logext.py
  dosagelib/output.py
  dosagelib/plugins/tapas.py
  dosagelib/scraper.py
  dosagelib/singleton.py
  dosagelib/util.py
  pyproject.toml
  tests/test_dosage.py
Labels: enhancement, chore

#343 Ignore "global" rules in robots.txt
  README.md
  dosagelib/http.py
  dosagelib/util.py
  scripts/keenspot.py
  tests/test_robotstxt.py
Labels: enhancement

#344 Add HTTP compression supported by requests as optional dependencies
  Jenkinsfile
  README.md
  pyproject.toml
  tests/modules/testall.sh
  tox.ini
Labels: dependencies, chore

#345 Start migration from CodeClimate to qlty.sh
  .github/workflows/ci.yaml
  README.md
  tox.ini
Labels: chore
